[tools]
# go = "latest"
# hugo-extended = "latest"
bat = "latest"
btop = "latest"
zoxide = "latest"
doggo = "latest"
tmux = "latest"
lazygit = "latest"
lazydocker = "latest"
kubectl = "latest"
k9s = "latest"
